# Import required libraries
import pandas as pd
# import numpy as np
from sklearn import metrics

import config
import model_dispatcher

# Function fitting model based on given dataframe
def initModel(model, df: pd.DataFrame):
    
    # Data initialization
    train_data = df.drop(columns="label")
    train_label = df["label"]

    # Fitting model
    model.fit(train_data, train_label)

# Function returning predicted data generated by model
def testModel(model, df: pd.DataFrame):

    # Data initialization
    test_data = df.drop(columns="label")

    # Predicting data and returning predicted data
    predicted_data = model.predict(test_data)
    return predicted_data

# Main function
if __name__ == "__main__":

    # Load and initialize data
    df = pd.read_csv(config.NEW_DATA_PATH)
    df.drop(columns=["id"])

    # Loop through all models
    for model_name in model_dispatcher.model_names:
        model = model_dispatcher.models[model_name]

        # Test single model on different folds
        for fold in range(config.SPLITS):
            
            # Initialize train dataframe and test dataframe
            df_train = df.loc[df["kfold"] != fold, :].reset_index(drop=True)
            df_test = df.loc[df["kfold"] == fold, :].reset_index(drop=True)

            df_train.drop(columns=["kfold"])
            df_test.drop(columns=["kfold"])

            # Initialize model
            initModel(model, df_train)

            # Test model and get results
            predicted_data = testModel(model, df_test)

            # Calculate and print accuracy score
            accuracy = metrics.accuracy_score(
                y_true=df_test["label"],
                y_pred=predicted_data
            )
            print(f"{model_name}: {fold} - {accuracy}")